helm:
  parameters:
  - name: image.tag
    value: "2362265"
    forcestring: true
  - name: image.name
    value: us-central1-docker.pkg.dev/responsive-amp-408809/my-repository/hello-cloudbuild
    forcestring: true
